### ISSUE TITLE
The input of LRpair?

### ISSUE THREAD

**Issue by TYCice** [liuqivandy/SpaGene#4]
Hi, dear developer,
You mentioned that  LR pair were downloaded from CellTalkDB. I followed the procedures from the tutorial but cannot get the results from SpaGene_LR function. I am not sure if the problem due to the input format of the LRpair. It's a dataframe directly download from CellTalkDB or a list with LRpair names? 

SpaGene_LR(count,location2,LRpair=LR_pair)  
[human_lr_pair.txt](https://github.com/liuqivandy/SpaGene/files/9899977/human_lr_pair.txt)

**Comment by liuqivandy** [comment]
It is a data frame, directly download from CellTalkDB.
I attached the object here, you can load(LRpair_human.rds”).
Feel free to let me know if you have any questions.
Best,
Qi

From: TYCice ***@***.***>
Date: Monday, October 31, 2022 at 4:52 AM
To: liuqivandy/SpaGene ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [liuqivandy/SpaGene] The input of LRpair? (Issue #4)

Hi, dear developer,
You mentioned that LR pair were downloaded from CellTalkDB. I followed the procedures from the tutorial but cannot get the results from SpaGene_LR function. I am not sure if the problem due to the input format of the LRpair. It's a dataframe directly download from CellTalkDB or a list with LRpair names?

SpaGene_LR(count,location2,LRpair=LR_pair)
human_lr_pair.txt<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliuqivandy%2FSpaGene%2Ffiles%2F9899977%2Fhuman_lr_pair.txt&data=05%7C01%7Cqi.liu%40vanderbilt.edu%7C08d8efdccc0c476a26d908dabb258e48%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C638028067228704783%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2C9ejsmgDmSuNp%2BUxAZ3aSgRI2m37pULCDjOEiWtDDA%3D&reserved=0>
